# permissions for end users to view fabrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fabric-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: yangtze
    app.kubernetes.io/part-of: yangtze
    app.kubernetes.io/managed-by: kustomize
  name: fabric-viewer-role
rules:
- apiGroups:
  - network.yangtze.xflops.cn
  resources:
  - fabrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.yangtze.xflops.cn
  resources:
  - fabrics/status
  verbs:
  - get
