apiVersion: apps/v1
kind: Deployment
metadata:
  name: yangtze-session-manager
  labels:
    app.kubernetes.io/name: yangtze-session-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: yangtze-session-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yangtze-session-manager
    spec:
      containers:
      - name: fsm
        image: registry.minikube/yangtze-session-manager:latest
        env:
        - name: RUST_LOG
          value: "info"
        - name: FLM_SM_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: flame-conf
          mountPath: /root/.flame
      volumes:
      - name: flame-conf
        configMap:
          name: flame-conf